### ISSUE TITLE
Service for task/solve api

### ISSUE THREAD

**Issue by Jeanosis** [Jeanosis/IntelligentSystemsLabs#35]
Service for task/solve api needs to be implemented.
Example: `app/first-lab/task/person.service.ts`
Logic:
POST method sends task and input parameters values, gets object:
```
[
   {
       "name": "out_var_n"
       "graph": {
          "values": [numbers],
          "step": number
       }
       "gravity_center": number
   },
   ...
]
```

**UPD:**
It required changes in server-side models and the JsonParser.Parser class, so it seems sensible, to move #31's tasks here.

- Models of JsonParser library are not just used by that library, so they should move to src/Models.
- The library has method InputsFromJson, that can be rewritten and used in api method, instead of parsing input right there

**UPD2:**
Service works, but we start all the enums with 1 instead of 0. This is apparently due to wrong code in TS-models' constructors (`||` part probably changes valid for enums `0`'s to `null`'s, which server-side code does not appriciate), but any attempt to fix it leads to some serious debugging process, so it will be put as a new task (see #39).

**Comment by harrytallbelt** [comment]
Done (see #38)
